src/main/java/edu/iit/sat/itmd4515/spuranik/domain/Employee.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.spuranik.domain;

import edu.iit.sat.itmd4515.spuranik.domain.security.User;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Employee Entity which consist of employee attributes with proper validation using annotation.
 * Named query to find using specific attribute
 * @author Pooja
 */
@Entity
@Table(name = "Employee")
@NamedQueries({
    @NamedQuery(name = "Employee.findAll", query = "select e from Employee e")
    ,
    @NamedQuery(name = "Employee.findByEmail", query = "SELECT c from Employee c WHERE c.email = :email")
     ,
    @NamedQuery(name = "Employee.findByUsername", query = "select p from Employee p where p.user.userName = :username")   
})
public class Employee extends BaseEntity{
    @Id@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Size(min = 4, max = 50, message = "Firstname should be between {min} and {max}")
    private String firstName;
    
    private String lastName;
    
    
    @NotNull(message = "The email cannot be null")
    @Column(unique = true)
    private String email;
   
    private long contactNo;
   
    private String address;
    
    @OneToOne
    @JoinColumn(name = "USERNAME")
    private User user;
     
    public User getUser() {
        return user;
    }

    /**
     * Set the value of user
     *
     * @param user new value of user
     */
    public void setUser(User user) {
        this.user = user;
    }
    /**
     * Get the value of address
     *
     * @return the value of address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Set the value of address
     *
     * @param address new value of address
     */
    public void setAddress(String address) {
        this.address = address;
    }


    /**
     * Get the value of password
     *
     * @return the value of password
     */
    


   

    public Employee() {
    }

    @Override
    public String toString() {
        return "Employee{" + "id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email + ", contactNo=" + contactNo + ", address=" + address + '}';
    }

   

    public Employee(String firstName, String lastName, String email, long contactNo, String address) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.contactNo = contactNo;
        this.address = address;
    }

   

  
  

    
    

   

    

    

    /**
     * Get the value of isadmin
     *
     * @return the value of isadmin
     */
    

    /**
     * Get the value of contactNo
     *
     * @return the value of contactNo
     */
    public long getContactno() {
        return contactNo;
    }

    /**
     * Set the value of contactNo
     *
     * @param contactNo new value of contactNo
     */
    public void setContactno(long contactNo) {
        this.contactNo = contactNo;
    }

    /**
     * Get the value of email
     *
     * @return the value of email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set the value of email
     *
     * @param email new value of email
     */
    public void setEmail(String email) {
        this.email = email;
    }
    /**
     * Get the value of lastName
     *
     * @return the value of lastName
     */
    public String getLastname() {
        return lastName;
    }

    /**
     * Set the value of lastName
     *
     * @param lastName new value of lastName
     */
    public void setLastname(String lastName) {
        this.lastName = lastName;
    }



    /**
     * Get the value of firstName
     *
     * @return the value of firstName
     */
    public String getFirstname() {
        return firstName;
    }

    /**
     * Set the value of firstName
     *
     * @param firstName new value of firstName
     */
    public void setFirstname(String firstName) {
        this.firstName = firstName;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    
    
}

src/main/java/edu/iit/sat/itmd4515/spuranik/domain/Product.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//////
package edu.iit.sat.itmd4515.spuranik.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;
/**
 * *Product Entity which consist of Product attributes with proper validation using annotation.
 * Named query to find using specific attribute
 * @author Pooja
 */
@Entity
@Table(name = "Product")
@NamedQueries({
    @NamedQuery(name = "Product.findAll", query = "select u from Product u")
    ,
    @NamedQuery(name = "Product.findByProductname", query = "SELECT u from Product u WHERE u.productname = :productname")
})
public class Product {

    @Id@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @NotNull(message = "The product cannot be null")
    @Column(unique = true)
    private String productname;
    
    private String categoryname;
    
        private String image;

    /**
     * Get the value of image
     *
     * @return the value of image
     */
    public String getImage() {
        return image;
    }

    /**
     * Set the value of image
     *
     * @param image new value of image
     */
    public void setImage(String image) {
        this.image = image;
    }

    private Float price;
    
   @Size(max = 2000)
    private String summary;
    
    private Long productquantity;
    
    private String genre;
    
    @Past
    @Temporal(TemporalType.DATE)
    private Date yop;
    
    private String author;
    
  
    public Product() {
    }

    public Product(String productname, String genre, Date yop, String author) {
        this.productname = productname;
        this.genre = genre;
        this.yop = yop;
        this.author = author;
    }

    public Product(String productname, Date yop) {
        this.productname = productname;
        this.yop = yop;
    }

    public Product(String productname, String categoryname, Float price, String summary, Long productquantity, String genre, Date yop, String author) {
        this.productname = productname;
        this.categoryname = categoryname;
        this.price = price;
        this.summary = summary;
        this.productquantity = productquantity;
        this.genre = genre;
        this.yop = yop;
        this.author = author;
    }

    @Override
    public String toString() {
        return "Product{" + "id=" + id + ", productname=" + productname + ", categoryname=" + categoryname + ", price=" + price + ", summary=" + summary + ", productquantity=" + productquantity + ", genre=" + genre + ", yop=" + yop + ", author=" + author + '}';
    }
    

    /**
     * Get the value of author
     *
     * @return the value of author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Set the value of author
     *
     * @param author new value of author
     */
    public void setAuthor(String author) {
        this.author = author;
    }


    /**
     * Get the value of yop
     *
     * @return the value of yop
     */
    public Date getYop() {
        return yop;
    }

    /**
     * Set the value of yop
     *
     * @param yop new value of yop
     */
    public void setYop(Date yop) {
        this.yop = yop;
    }

    /**
     * Get the value of genre
     *
     * @return the value of genre
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Set the value of genre
     *
     * @param genre new value of genre
     */
    public void setGenre(String genre) {
        this.genre = genre;
    }

    /**
     * Get the value of productquantity
     *
     * @return the value of productquantity
     */
    public Long getProductquantity() {
        return productquantity;
    }
    

    /**
     * Set the value of productquantity
     *
     * @param productquantity new value of productquantity
     */
    public void setProductquantity(Long productquantity) {
        this.productquantity = productquantity;
    }
    

    /**
     * Get the value of summary
     *
     * @return the value of summary
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Set the value of summary
     *
     * @param summary new value of summary
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Get the value of price
     *
     * @return the value of price
     */
    public Float getPrice() {
        return price;
    }

    /**
     * Set the value of price
     *
     * @param price new value of price
     */
    public void setPrice(Float price) {
        this.price = price;
    }


    /**
     * Get the value of categoryname
     *
     * @return the value of categoryname
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * Set the value of categoryname
     *
     * @param categoryname new value of categoryname
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    

    /**
     * Get the value of productname
     *
     * @return the value of productname
     */
    public String getProductname() {
        return productname;
    }

    /**
     * Set the value of productname
     *
     * @param productname new value of productname
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    
    
    
    
    
}

src/main/java/edu/iit/sat/itmd4515/spuranik/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.spuranik.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 * Login Controller extending Base Controller consists of enterprise bean, post
 * construct Login Controller is used to define the roles like Admin role Cust
 * role and Emp role for Admin customer employee doLogin and doLogout which uses
 * http Servlet request
 *
 * @author Pooja
 */
@Named
@RequestScoped
public class LoginController extends BaseController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    public LoginController() {
    }
    @NotNull(message = "Please enter a username.")
    private String username;
    @NotNull(message = "Please enter a password.")
    private String password;

    //utility methods
    public String getRemoteUser() {
        return context.getExternalContext().getRemoteUser();
    }

    public boolean isAdmin() {
        return context.getExternalContext().isUserInRole("ADMIN_ROLE");
    }

    public boolean isCustomer() {
        return context.getExternalContext().isUserInRole("CUST_ROLE");
    }

    public boolean isEmployee() {
        return context.getExternalContext().isUserInRole("EMP_ROLE");
    }

    public String doLogin() {
        HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();

        try {
            req.login(username, password);
        } catch (ServletException ex) {
            //login failed
            LOG.log(Level.SEVERE, null, ex);
            //provide error message
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Login", "User or Password not valid"));
            //send back to the login page
            return "/login.xhtml";
        }
        return "/welcome.xhtml?faces-redirect=true";
    }

    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();
        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            //mESSAGE ON FAILED LOGIN
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed Logout", "You have Failed to Logout"));
            //send back to the login page
            return "/login.xhtml";
        }
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "You have logged out", "You have logged out successfully.  Please don't forget to close your browser."));
        return "/login.xhtml";
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

}

src/main/webapp/employee/createProduct.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <body>

        <ui:composition template="./../WEB-INF/templates/authnTemplate.xhtml">

            <ui:define name="title">
                <h2> New Product</h2>
            </ui:define>
            <ui:define name="content">
                <ezcomp:product
                    product="#{employeePortalController.product}" 
                    readonly="false"
                    action="#{employeePortalController.doExecutenewProduct()}"/>
                <h:link class="btn btn-lg btn-primary" outcome="/employee/welcome.xhtml" value="Back"/> 
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/employee/editOrder.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <body>

        <ui:composition template="./../WEB-INF/templates/authnTemplate.xhtml">

            <ui:define name="title">
                <h2> Review Order </h2>
            </ui:define>
            <ui:define name="content">
                <ezcomp:employeeorder 
                    order="#{employeePortalController.ordertable}" 
                    readonly="false"
                    action="#{employeePortalController.doExecuteupdate()}"/>
                <h:link class="btn btn-lg btn-primary" outcome="/employee/welcome.xhtml" value="Back"/> 
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/employee/product.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authnTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        <h2>Products</h2>
    </ui:define>

    <ui:define name="content">
        <div class="jumbotron">
            <h1>Employee Welcome</h1>
            <p>Hello employee #{loginController.remoteUser}</p>
            <a class="btn btn-lg btn-primary" href="#" role="button">View more about WordsWorth</a>
            <h:form>
                <h:commandLink class="btn btn-lg btn-primary" action="#{employeePortalController.docreateProduct()}" value="Add New Product"/>
            </h:form>

        </div>
        <h2>Product Details</h2>

        <h:dataTable class="table table-striped table-hover" value="#{productService.findAll()}" var="product">

            <h:column>
                <f:facet name="header">
                    <h:outputText value="ID"/>
                </f:facet>
                <h:outputText value="#{product.id}">
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Product Name"/>
                </f:facet>
                <h:outputText value="#{product.productname}">
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Category"/>
                </f:facet>
                <h:outputText value="#{product.categoryname}">
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Price($)"/>
                </f:facet>
                <h:outputText value="#{product.price}">
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header" >
                    <h:outputText value="Price(INR)"/>
                </f:facet>
                <h:outputText value="#{product.price}">
                    <f:converter converterId="rupeeConverter">
                    </f:converter>
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Quantity"/>
                </f:facet>
                <h:outputText value="#{product.productquantity}">
                </h:outputText>
            </h:column>

        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/employee/viewOrder.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <body>

        <ui:composition template="./../WEB-INF/templates/authnTemplate.xhtml">

            <ui:define name="title">
                <h2>View Order</h2>
            </ui:define>

            <ui:define name="content">
                <ezcomp:employeeorder 
                    order="#{employeePortalController.ordertable}"
                    readonly="true"/>
                <h:link class="btn btn-lg btn-primary" outcome="/employee/welcome.xhtml" value="Back"/> 
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/employee/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/authnTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">

    </ui:define>

    <ui:define name="content">
        <div class="jumbotron">
            <h1>Employee Welcome</h1>
            <p>Hello employee #{loginController.remoteUser}</p>
            <a class="btn btn-lg btn-primary" href="#" role="button">View more about WordsWorth</a>
            <h:form>
                <h:commandButton class="btn btn-lg btn-primary" action="#{employeePortalController.taketoProduct()}" value="Products"/>
            </h:form>

        </div>

        <h2>Employee Details</h2>
        <h:dataTable class="table table-striped table-bordered table-hover" value="#{employeeService.findByUsername(loginController.remoteUser)}" var="employee">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="ID"/>
                </f:facet>
                <h:outputText value="#{employee.id}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="FirstName"/>
                </f:facet>
                <h:outputText value="#{employee.firstname}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="LastName"/>
                </f:facet>
                <h:outputText value="#{employee.lastname}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="ContactNo"/>
                </f:facet>
                <h:outputText value="#{employee.contactno}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Address"/>
                </f:facet>
                <h:outputText value="#{employee.address}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="EmailId"/>
                </f:facet>
                <h:outputText value="#{employee.email}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Username"/>
                </f:facet>
                <h:outputText value="#{employee.user.userName}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header">
                    <h:outputText value="Registered Date"/>
                </f:facet>
                <h:outputText value="#{employee.registeredDate}">
                    <f:convertDateTime type="both" dateStyle="short" timeStyle="full" timeZone="#{appConfig.timeZone}"/>
                </h:outputText>
            </h:column>
        </h:dataTable>
        <h2>Orders</h2>
        <h:dataTable class="table table-hover table-bordered " value="#{employeePortalController.getallOrders()}" var="ordertable">
            <h:column>
                <f:facet name="header" >
                    <h:outputText value="ID"/>
                </f:facet>
                <h:outputText value="#{ordertable.id}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header">
                    <h:outputText value="Customer Name"/>
                </f:facet>
                <h:outputText value="#{ordertable.getCustomer().getFirstname()}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header">
                    <h:outputText value="Total Price in $"/>
                </f:facet>
                <h:outputText value="#{ordertable.totalprice}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header" >
                    <h:outputText value="Total Price in INR"/>
                </f:facet>
                <h:outputText value="#{ordertable.totalprice}">
                    <f:converter converterId="rupeeConverter">
                    </f:converter>
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Click"/>
                </f:facet>
                <h:form>
                    <h:commandLink action="#{employeePortalController.doViewOrder(ordertable)}" value="View "/>
                    <h:commandLink action="#{employeePortalController.doReviewOrder(ordertable)}" value="Update "/>
                </h:form>
            </h:column>
        </h:dataTable>
    </ui:define>

</ui:composition>